services:
  app:
    build: .
    ports:
      - "[::]:80:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    restart: always
  db:
    image: postgres:18.1
    ports:
      - "[::]:5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    restart: always

volumes:
  db_data: